export const PLACES_PATH = '/places'
export const USERS_PATH = '/users'
export const PLANNER_PATH = '/planners'
export const ME_PATH = '/me'
export const SEARCH_PATH = '/search'
export const EVENTS_PATH = '/events'
